CXX = g++
CXXFLAGS = -std=c++17 -Wall -I./include
OBJDIR = obj/src
SRCDIR = src
TARGET = bfs_exec

SRC = $(SRCDIR)/main.cpp $(SRCDIR)/bfs.cpp
OBJ = $(OBJDIR)/main.o $(OBJDIR)/bfs.o

all: $(TARGET)

$(TARGET): $(OBJ)
	$(CXX) $(CXXFLAGS) -o $@ $^

$(OBJDIR)/%.o: $(SRCDIR)/%.cpp | $(OBJDIR)
	$(CXX) $(CXXFLAGS) -c $< -o $@

$(OBJDIR):
	mkdir -p $(OBJDIR)

clean:
	rm -rf $(OBJDIR) $(TARGET)
